# Generated by Django 6.0.1 on 2026-01-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apipractice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=200),
        ),
    ]
