# Generated by Django 6.0.1 on 2026-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apipractice", "0002_alter_customer_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("roll_no", models.IntegerField(max_length=10, unique=True)),
                ("father_name", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=150)),
            ],
        ),
    ]
