# Generated by Django 6.0.1 on 2026-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apipractice", "0003_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(max_length=10)),
                ("field", models.CharField(max_length=50)),
                ("work", models.CharField(max_length=100)),
            ],
        ),
    ]
