# Generated by Django 6.0.1 on 2026-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apipractice", "0004_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("manage", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="work",
            new_name="role",
        ),
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_no",
            field=models.IntegerField(unique=True),
        ),
    ]
