# Generated by Django 5.2.7 on 2025-10-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
