# Generated by Django 5.2.7 on 2025-10-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Api", "0002_alter_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(),
        ),
    ]
